before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- id: sod
  main: ./cmd/sod-srv
  binary: sod
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goos:
    - freebsd
    - linux
    - windows
    - darwin
  ldflags:
    - -s -w -X main.version={{.Version}} -extldflags '-static'
archives:
  - id: sod
    builds:
      - sod
    name_template: "sod_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: MacOSX
      linux: Linux
      windows: Windows
      amd64: x86_64

nfpms:
  - vendor: sod
    homepage: https://github.com/go-sod/sod
    maintainer: Nikita Ivanov
    description: Recognition of anomalies in the data stream in real time. Identify peaks. Fraud detection.
    license: MIT
    formats: [ deb, rpm ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: go-sod
    name: sod